spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres5
    username: postgres5
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
upload:
  server:
    folder: \\Users\\gayrat\\Documents\\upload

api:
  jsonplaceholder: https://jsonplaceholder.typicode.com

jwt:
  token:
    secret: hellojwttoken
    validity: 86400000

